server:
  port: 8899

## ===== logback日志默认默认输出到控制台，配置本地存放路径和日志文件信息 ===== #
logging:
  file:
    name: userManager.log
    path: logs

# ===== spring配置信息 ===== #
spring:
  application:
    name: userManager
  profiles:
    active: dev
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?serverTimezone=GMT&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 123456

# ===== mybatis配置信息 ===== #
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*

